#!/bin/bash

# default options
a="-a 0.0.0.0"
c="-c-1"
cors="--cors"
i="-i false"
port="-p 8080"
options="--no-dotfiles"

# override default options
while test ${#} -gt 0
do
    if [[ "$1" =~ ^-a$ ]]; then
        a="$1 $2"
        shift
        shift
    elif [[ "$1" =~ ^-c-?[0-9]+$ ]]; then
        c="$1"
        shift
    elif [[ "$1" =~ ^--cors(=.*)?$ ]]; then
        cors="$1"
        shift
    elif [[ "$1" =~ ^-i$ ]]; then
        i="$1 $2"
        shift
        shift
    elif [[ "$1" =~ ^-p[^\s]+ ]]; then
        port="$1"
        shift
    elif [[ "$1" == "-p" ]]; then
        port="$1 $2"
        shift
        shift
    else
        options+=" $1"
        shift
    fi
done

# kill any process listing on the specified port
# regex to handle -pxxxx, -p xxxx
fuser --kill "${port//[^0-9]}/tcp" &> /dev/null

# spawn http-server, retaining colorized output
script --flush --quiet --return /dev/null --command "/usr/local/bin/http-server $a $c $cors $i $port $options" |
    while IFS= read -r line
    do
        # rewrite address(es) as localhost
        if [[ "$line" =~ "Available on:" ]]; then
            echo "$line"
            IFS= read -r line
            echo "$line" | sed "s#\(.*http://\)[^:]\+\(:.\+\)#\1localhost\2#"
            while IFS= read -r line
            do
                if [[ "$line" =~ "Hit CTRL-C to stop the server" ]]; then
                    echo "$line"
                    break
                fi
            done
        else
            echo "$line"
        fi
    done
